= Passer sur la bêta de Jeedom et des plugins

[IMPORTANT]
L'activation des bêtas est très très risquée et vous INTERDIT TOUT ACCES AU SUPPORT. IL faut aussi obligatoirement passer Jeedom en bêta et faire des mises à jour fréquentes même s'il n'y a pas de nouvelles mises à jour proposées. IMPORTANT, les versions bêtas sont souvent instables et peuvent causer de nombreux soucis, il ne faut surtout pas les mettre sur un système de production. EN CAS DE SOUCIS, L'EQUIPE JEEDOM NE SERA PAS ET NE POURRA PAS ETRE TENUE RESPONSABLE.

[NOTE]
Cette documentation est volontairement peu détaillée pour que l'opération ne soit pas facile, en effet être en bêta nécessite des compétences aussi bien en informatique qu'en déchiffrage de logs ou documentation.

== Passer le core en bêta

Il faut d'abord passer Jeedom en version bêta. Pour cela, vérifiez que vous êtes bien en mode expert, puis dans l'administration de Jeedom, aller dans "Mises à jour et fichiers". Puis dans l'onglet github, cliquer sur Activer :

- Utilisateur ou organisation du dépôt pour le core Jeedom : jeedom
- Nom du dépôt pour le core Jeedom : core
- Branche pour le core Jeedom : beta

Sauvegarder puis réactualiser la page. Toujours dans la partie "Mises à jour et fichiers", dans "Source de mise à jour" sélectionner "Github".

Il ne vous reste plus qu'à forcer une mise à jour du core pour passer sur la version bêta de Jeedom.

[IMPORTANT]
Jeedom ne signale en bêta que les mises à jour importantes, il vous faudra donc souvent forcer la mise à jour de Jeedom pour avoir la dernière version, même si le Centre de mises à jour ne vous propose rien.

[IMPORTANT]
Une mise à jour en bêta peut complètement casser votre Jeedom et le rendre irrécupérable, en cas de souci vous n'avez AUCUN SUPPORT, il faudra vous débrouiller à l'aide de vos propres compétences.

[IMPORTANT]
Le passage d'une version stable à une version bêta est risqué (nous ne garantissons jamais que votre Jeedom continue de fonctionner correctement). Le passage d'une version bêta à une version stable est INTERDIT, en effet, lors d'une telle opération, il est sûr à 100% que votre Jeedom sera cassé. Il n'est pas possible de faire un retour arrière en restaurant un backup d'une version stable. En cas de souci, vous ne bénéficierez d'AUCUN SUPPORT.

== Passer les plugins en bêta

Pour cela, il faut vous rendre sur le Market Jeedom, puis dans votre profil, partie "Mes Jeedoms", cocher la case pour avoir accès aux plugins en version bêta.

Ensuite, dans votre Jeedom, sur les fiches des plugins, vous devriez voir un bouton "Installer bêta".

[IMPORTANT]
Tout plugin installé en version bêta interdit l'accès complet au support, même si votre problème ne concerne pas ce plugin.

[IMPORTANT]
Un plugin en version stable peut ne pas marcher sur un Jeedom bêta.

[IMPORTANT]
Un plugin en version bêta NE FONCTIONNE PAS sur un Jeedom stable.

[IMPORTANT]
Toute demande de support portant sur la façon de passer en bêta, sur un souci avec un composant en bêta ou sur un système ayant déjà eu un core ou un plugin en bêta, sera immediatement fermé sans aucune réponse de notre part.
